CREATE TABLE users (
  id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  confirmed boolean NOT NULL DEFAULT false,
  email varchar(1024) NOT NULL,
  password varchar(1024) NOT NULL,
  "name" varchar(255) NOT NULL,
  confirm_selector varchar(1024),
  confirm_verifier varchar(1024),
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX index_users_email ON users (lower(email));
