CREATE TABLE records (
  id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  broadcaster_id bigint NOT NULL,
  uuid varchar(255) NOT NULL,
  created_at timestamp with time zone NOT NULL,
  finish_at  timestamp with time zone
);

ALTER TABLE records ADD CONSTRAINT fk_records_broadcaster_id
  FOREIGN KEY (broadcaster_id) REFERENCES broadcasters(id) ON DELETE CASCADE;

CREATE INDEX index_records_broadcaster_id ON records (broadcaster_id);
