BEGIN;
  CREATE TYPE farm_state AS ENUM (
    'inactive',
    'active',
    'failed'
  );

  CREATE TABLE farms (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    state farm_state NOT NULL DEFAULT 'inactive'
  );

  COMMENT ON TABLE farms IS 'Аккаунты на портале, с подписками - "фермы с дойными коровами"';

  ALTER TABLE broadcasters ADD COLUMN farm_id bigint;
  ALTER TABLE broadcasters ADD CONSTRAINT fk_broadcasters_farm_id FOREIGN KEY (farm_id)
    REFERENCES farms(id);
  CREATE INDEX index_broadcasters_farm_id ON broadcasters (farm_id);
COMMIT;
