version: '3.2'

services:
  saverbate-pg:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: ${SAVERBATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SAVERBATE_POSTGRES_PASSWORD}
      POSTGRES_DB: saverbate_records
    restart: "unless-stopped"
    expose:
      - "5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/dumps:/docker-entrypoint-initdb.d:ro
    networks:
      - default
      - backend
    depends_on:
      - saverbate-db
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-db:
    image: edoburu/pgbouncer
    environment:
      DATABASE_URL: postgres://${SAVERBATE_POSTGRES_USER}:${SAVERBATE_POSTGRES_PASSWORD}@saverbate-pg/saverbate_records
      POOL_MODE: session
      MAX_CLIENT_CONN: 100
    expose:
      - "5432"
    ports:
      - "10532:5432"
    volumes:
      - ~/.pgpass:/root/.pgpass
    networks:
      - default
      - backend
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

volumes:
  pg-data:
    driver: local

networks:
  frontend:
    external:
      name: frontend

  backend:
    external:
      name: backend
