version: '3.2'

services:
  saverbate-nats:
    image: nats
    volumes:
      - ./configs/nats:/configs
    expose:
      - 4222
    ports:
      - "10222:4222"
    networks:
      - default
      - backend
    command: -D --config /configs/nats-server.conf
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-redis:
    image: redis
    expose:
      - 6379
    networks:
      - default
      - backend
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-pg:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: ${SAVERBATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SAVERBATE_POSTGRES_PASSWORD}
      POSTGRES_DB: saverbate_records
    restart: "unless-stopped"
    expose:
      - "5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/dumps:/docker-entrypoint-initdb.d:ro
    networks:
      - default
      - backend
    depends_on:
      - saverbate-db
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-db:
    image: edoburu/pgbouncer
    environment:
      DATABASE_URL: postgres://${SAVERBATE_POSTGRES_USER}:${SAVERBATE_POSTGRES_PASSWORD}@saverbate-pg/saverbate_records
      POOL_MODE: session
      MAX_CLIENT_CONN: 90
    expose:
      - "5432"
    ports:
      - "10532:5432"
    volumes:
      - ~/.pgpass:/root/.pgpass
    networks:
      - default
      - backend
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-frontend:
    build:
      context: .
      args:
        SERVICE_NAME: frontend
    environment:
      POSTGRES_USER: ${SAVERBATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SAVERBATE_POSTGRES_PASSWORD}
      POSTGRES_DB: saverbate_records
    expose:
      - "80"
    networks:
      - default
      - frontend
      - backend
    depends_on:
      - saverbate-db
      - saverbate-nats
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-downloader:
    build:
      context: .
      dockerfile: Dockerfile-downloader
    environment:
      POSTGRES_USER: ${SAVERBATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SAVERBATE_POSTGRES_PASSWORD}
      POSTGRES_DB: saverbate_records
    networks:
      - default
      - backend
    depends_on:
      - saverbate-db
      - saverbate-nats
    restart: "unless-stopped"
    command: /app/service --natsAddress nats://saverbate-nats:4222
    volumes:
      - ./downloads:/app/downloads
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-mailer:
    build:
      context: .
      args:
        SERVICE_NAME: mailer
    networks:
      - default
      - backend
    depends_on:
      - saverbate-redis
      - saverbate-nats
      - saverbate-db
    restart: "unless-stopped"
    command: /app/service --natsAddress nats://saverbate-nats:4222
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-crawler:
    build:
      context: .
      dockerfile: Dockerfile-parsers
      args:
        SERVICE_NAME: crawler
    networks:
      - default
      - backend
    depends_on:
      - saverbate-pg
      - saverbate-redis
    restart: "unless-stopped"
    command: /parsers/service --pydbconn pq://${SAVERBATE_POSTGRES_USER}:${SAVERBATE_POSTGRES_PASSWORD}@saverbate-pg:5432/saverbate_records
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-scraper:
    build:
      context: .
      dockerfile: Dockerfile-parsers
      args:
        SERVICE_NAME: scraper
    networks:
      - default
      - backend
    depends_on:
      - saverbate-pg
      - saverbate-redis
    restart: "unless-stopped"
    command: /parsers/service --pydbconn pq://${SAVERBATE_POSTGRES_USER}:${SAVERBATE_POSTGRES_PASSWORD}@saverbate-pg:5432/saverbate_records
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

volumes:
  pg-data:
    driver: local

networks:
  frontend:
    external:
      name: frontend

  backend:
    external:
      name: backend
