version: '3.2'

services:
  saverbate-nats:
    image: nats
    volumes:
      - ./configs/nats:/configs
    expose:
      - 4222
    ports:
      - "10222:4222"
    networks:
      - default
      - backend
    command: -D --config /configs/nats-server.conf
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-redis:
    image: redis
    expose:
      - 6379
    networks:
      - default
      - backend
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-pg:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: ${SAVERBATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SAVERBATE_POSTGRES_PASSWORD}
      POSTGRES_DB: saverbate_records
    restart: "unless-stopped"
    expose:
      - "5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/dumps:/docker-entrypoint-initdb.d:ro
    networks:
      - default
      - backend
    depends_on:
      - saverbate-db
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-pg-backup:
    build:
      context: ./deployments/postgres-backup-s3
    image: saverbate/postgres-backup-s3:latest
    depends_on:
      - saverbate-pg
    restart: "unless-stopped"
    networks:
      - default
      - backend
    environment:
      POSTGRES_HOST: saverbate-pg
      POSTGRES_USER: ${SAVERBATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SAVERBATE_POSTGRES_PASSWORD}
      POSTGRES_DATABASE: saverbate_records
      SCHEDULE: '@daily'
      S3_REGION: ru-msk
      S3_ACCESS_KEY_ID: ${SAVERBATE_MAILRU_S3_ID}
      S3_SECRET_ACCESS_KEY: ${SAVERBATE_MAILRU_S3_SECRET}
      S3_BUCKET: ${SAVERBATE_MAILRU_BACKUP_BACKET}
      S3_PREFIX: backup
      S3_ENDPOINT: https://hb.bizmrg.com
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-db:
    image: edoburu/pgbouncer
    environment:
      DATABASE_URL: postgres://${SAVERBATE_POSTGRES_USER}:${SAVERBATE_POSTGRES_PASSWORD}@saverbate-pg/saverbate_records
      POOL_MODE: session
      MAX_CLIENT_CONN: 90
    expose:
      - "5432"
    ports:
      - "10532:5432"
    volumes:
      - ~/.pgpass:/root/.pgpass
    networks:
      - default
      - backend
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-frontend:
    build:
      context: .
      args:
        SERVICE_NAME: frontend
    environment:
      POSTGRES_USER: ${SAVERBATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SAVERBATE_POSTGRES_PASSWORD}
      POSTGRES_DB: saverbate_records
    expose:
      - "80"
    networks:
      - default
      - frontend
      - backend
    depends_on:
      - saverbate-db
      - saverbate-nats
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-downloader:
    build:
      context: .
      dockerfile: Dockerfile-downloader
      args:
        SERVICE_NAME: downloader
    environment:
      POSTGRES_USER: ${SAVERBATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SAVERBATE_POSTGRES_PASSWORD}
      POSTGRES_DB: saverbate_records
    networks:
      - default
      - backend
    depends_on:
      - saverbate-db
      - saverbate-nats
      - saverbate-redis
    restart: "unless-stopped"
    command: /app/service --natsAddress nats://saverbate-nats:4222
    volumes:
      - ./downloads:/app/downloads
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-thumbnails:
    build:
      context: .
      dockerfile: Dockerfile-downloader
      args:
        SERVICE_NAME: thumbnails
    networks:
      - default
      - backend
    depends_on:
      - saverbate-nats
      - saverbate-redis
    restart: "unless-stopped"
    command: /app/service --natsAddress nats://saverbate-nats:4222
    volumes:
      - ./downloads:/app/downloads
      - ./scripts/thumbnail.sh:/usr/local/bin/thumbnail.sh:ro
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-mailer:
    build:
      context: .
      args:
        SERVICE_NAME: mailer
    networks:
      - default
      - frontend
      - backend
    depends_on:
      - saverbate-redis
      - saverbate-nats
      - saverbate-db
    restart: "unless-stopped"
    command: /app/service --natsAddress nats://saverbate-nats:4222 --listen 0.0.0.0:80
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=mailer.saverbate.$DOCKER_TLD
      - VIRTUAL_PATH=/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-crawler:
    build:
      context: .
      dockerfile: Dockerfile-parsers
      args:
        SERVICE_NAME: crawler
    networks:
      - default
      - backend
    depends_on:
      - saverbate-pg
      - saverbate-redis
    restart: "unless-stopped"
    command: /parsers/service --pydbconn pq://${SAVERBATE_POSTGRES_USER}:${SAVERBATE_POSTGRES_PASSWORD}@saverbate-pg:5432/saverbate_records
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-scraper:
    build:
      context: .
      dockerfile: Dockerfile-parsers
      args:
        SERVICE_NAME: scraper
    networks:
      - default
      - backend
    depends_on:
      - saverbate-pg
      - saverbate-redis
    restart: "unless-stopped"
    command: /parsers/service --pydbconn pq://${SAVERBATE_POSTGRES_USER}:${SAVERBATE_POSTGRES_PASSWORD}@saverbate-pg:5432/saverbate_records
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-vod:
    image: nytimes/nginx-vod-module
    restart: "unless-stopped"
    networks:
      - default
      - frontend
    ports:
      - "3005:80"
    volumes:
      - ./downloads:/opt/static/videos
      - ./configs/nginx-vod/nginx.conf:/usr/local/nginx/conf/nginx.conf
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  saverbate-imgproxy:
    image: darthsim/imgproxy:latest
    restart: "unless-stopped"
    volumes:
      - ./downloads:/static
    expose:
      - "80"
    networks:
      - frontend
    environment:
      - IMGPROXY_BIND=:80
      - IMGPROXY_QUALITY=98
      - VIRTUAL_HOST=imgproxy.saverbate.localhost
      - VIRTUAL_PATH=/
      - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/static
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

volumes:
  pg-data:
    driver: local

networks:
  frontend:
    external:
      name: frontend

  backend:
    external:
      name: backend
